server:
  port: 8989
  #本地实例运行端口

eureka:
  instance:
  #设置注册中心主机名
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
  #指示该客户端是否应从eureka服务器获取eureka注册表信息,默认为true
    fetch-registry: false
    #指示此实例是否应将其信息注册到eureka服务器以供其他人发现。在某些情况下，您不希望发现实例，而您只想发现其他实例，默认为true
    register-with-eureka: false
    #注意该链接host是指向本地实例的,可用性区域映射到与eureka服务器通信的完全限定URL的列表。
    #每个值可以是单个URL或逗号分隔的替代位置列表。
    #通常，尤里卡服务器URL携带协议，主机，端口，上下文和版本信息（如果有的话）。
    #示例：http : //ec2-256-156-243-129.compute-1.amazonaws.com : 7001/eureka/
    #更改在运行时在eurekaServiceUrlPollIntervalSeconds指定的下一个服务网址刷新周期中有效。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #指示从eureka服务器获取注册表信息的频率（以秒为单位）,默认30秒
    registry-fetch-interval-seconds: 30

  dashboard:
  #标志以启用Eureka仪表板。默认值为true。
    enabled: true
  #到Eureka仪表板（相对于servlet路径）的路径。默认为“/”。
    path: "/"
  server:
    #关闭eureka自我保护,防止自己注册自己，默认情况下是开启的
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000

debug: true