server:
#本地实例运行端口
  port: 8989


eureka:
  instance:
  #设置注册中心主机名
    hostname: localhost
    #指示eureka客户端需要向eureka服务器发送心跳以指示它仍然存在的频率（以秒为单位）。
    lease-renewal-interval-in-seconds: 1
    #指示eureka服务器在接收到最后一个心跳之后等待的时间（秒），然后才能从此视图中(eureka server的注册表)删除此实例，并禁止此实例的流量以提高系统的可用性。
    lease-expiration-duration-in-seconds: 2
  client:
  #指示该客户端是否应从eureka服务器获取eureka注册表信息,默认为true
    fetch-registry: false
    #指示此实例是否应将其信息注册到eureka服务器以供其他人发现。在某些情况下，您不希望发现实例，而您只想发现其他实例，默认为true
    register-with-eureka: false
    #注意该链接host是指向本地实例的,可用性区域映射到与eureka服务器通信的完全限定URL的列表。
    #每个值可以是单个URL或逗号分隔的替代位置列表。
    #通常，尤里卡服务器URL携带协议，主机，端口，上下文和版本信息（如果有的话）。
    #示例：http : //ec2-256-156-243-129.compute-1.amazonaws.com : 7001/eureka/
    #更改在运行时在eurekaServiceUrlPollIntervalSeconds指定的下一个服务网址刷新周期中有效。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #指示从eureka服务器获取注册表信息的频率（以秒为单位）,默认30秒
    registry-fetch-interval-seconds: 30

  dashboard:
  #标志以启用Eureka仪表板。默认值为true。
    enabled: true
  #到Eureka仪表板（相对于servlet路径）的路径。默认为“/”。
    path: "/"
  server:
    #关闭eureka自我保护,防止eureka server自己注册自己，默认情况下是开启的,搭建时需要注意,不关闭可能引起Server不踢出已关停节点的问题
    enable-self-preservation: false
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 40000
debug: true